backend:
  name: github
  repo: Jaspero/zoldos_group
  branch: master
  base_url: https://europe-west2-zoldos-group.cloudfunctions.net/
  auth_endpoint: /oauth/auth
publish_mode: editorial_workflow
media_folder: "public/uploads"
public_folder: "/uploads"
display_url: https://zoldos-group.web.app
logo_url: https://zoldos-group.web.app/assets/icons/logo.svg


# Reusable blocks for all of the pages
blocks: &blocks
  label: "Blocks"
  name: "blocks"
  widget: "list"
  types:
    - label: "Two Block Text"
      name: "twoBlockText"
      widget: "object"
      fields:
        - { label: "Name", name: "name", widget: "string", required: false }
        - { label: "Info", name: "info", widget: "string", required: false }
        - { label: "Bio", name: "bio", widget: "string", requried: true }
        - { label: "Bio Two", name: "bioTwo", widget: "string", requried: true }

    - label: "Landing block"
      name: "landingBlock"
      widget: "object"
      fields:
        - { label: "Title", name: "title", widget: "string", required: false }
        - { label: "Sub Title", name: "subTitle", widget: "string", required: false }
        - { label: "Image", name: "image", widget: "image", requried: true }

    - label: "Members Block"
      name: "membersBlock"
      widget: "object"
      fields:
        - { label: "Title", name: "title", widget: "string", required: false }
        - { label: "Image", name: "image", widget: "image", requried: true }
        - { label: "Description", name: "description", widget: "string", required: false }

    - label: "Contact Block"
      name: "contactBlock"
      widget: "object"
      fields:
        - { label: "Title", name: "title", widget: "string", required: false }
        - { label: "Image", name: "image", widget: "image", requried: true }
        - { label: "Description", name: "description", widget: "string", required: false }
        - { label: "Name", name: "name", widget: "string", required: false }
        - { label: "Subtitle", name: "subTitle", widget: "string", required: false }

    - label: "News Block"
      name: "newsBlock"
      widget: "object"
      fields:
        - { label: "Title", name: "title", widget: "string", required: false }
        - { label: "Subtitle", name: "subTitle", widget: "string", required: false }
        - { label: "Author", name: "author", widget: "string" }
        - { label: "Date", name: "date", widget: "string" }
        - { label: "Description", name: "description", widget: "text" }
        - { label: "Count", name: "count", widget: "number", requred: false }


    - label: "Researches Block"
      name: "researchesBlock"
      widget: "object"
      fields:
        - { label: "Title", name: "title", widget: "string", required: false }
        - { label: "Subtitle", name: "subTitle", widget: "string", required: false }
        - { label: "Count", name: "count", widget: "number", requred: false }

    - label: "Gallery Block"
      name: "galleryBlock"
      identifier_field: "year"
      fields:
        - label: "Year"
          name: "year"
          widget: "string"
        - label: "Images"
          name: "images"
          widget: "list"
          fields:
            - {label: Image, name: image, widget: image}


meta: &meta
  label: "Meta"
  name: "meta"
  widget: "object"
  fields:
    - { label: "Title", name: "title", widget: "string", required: false }
    - { label: "Description", name: "description", widget: "text", required: false }
    - { label: "Keywords", name: "keywords", widget: "string", required: false }

slug:
  encoding: "ascii"
  clean_accents: true
collections:
  - name: "settings"
    label: "Settings"
    extension: "json"
    format: "json"
    editor:
      preview: false
    files:
      - label: "Settings"
        name: "settings"
        file: "public/collections/settings.json"
        fields:
          - label: "Links"
            name: "links"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "text" }
              - { label: "Link", name: "link", widget: "text" }
      - label: "Home"
        name: "home"
        file: "public/collections/home.json"
        fields:
          - <<: *meta
          - <<: *blocks

  - name: "pages"
    label: "Pages"
    extension: "json"
    format: "json"
    folder: "public/collections/pages"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - <<: *meta
      - <<: *blocks

  - name: "researches"
    label: "Researches"
    folder: "public/collections/researches"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Thumbnail Image", name: "thumbImg", widget: "image" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Featured", name: "featured", widget: "boolean" }
      - <<: *meta
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "news"
    label: "News"
    folder: "public/collections/news"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Date", name: "date", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Thumbnail Image", name: "thumbImg", widget: "image" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Featured", name: "featured", widget: "boolean" }
      - <<: *meta
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "publications"
    label: "Publications"
    folder: "public/collections/publications"
    create: true
    slug: "{{slug}}"
    identifier_field: "year"
    editor:
      preview: false
    fields:
      - label: "Year"
        name: "year"
        widget: "number"
      - label: "Publications"
        name: "publications"
        widget: "list"
        fields:
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Link", name: "link", widget: "string" }

  - name: "photo-gallery"
    label: "Photo-gallery"
    folder: "public/collections/photo-gallery"
    create: true
    slug: "{{slug}}"
    identifier_field: "year"
    editor:
      preview: false
    fields:
      - { label: "Year", name: "year", widget: "number" }
      - { label: "Image", name: "image", widget: "image" }
      - label: "Image Gallery"
        name: "imageGallery"
        widget: "list"
        fields:
          - { label: "Thumbnail Image", name: "thumbImg", widget: "image" }
          - { label: "Full Image", name: "fullImg", widget: "image" }




  - name: "lab-members"
    label: "Lab-members"
    folder: "public/collections/lab-members"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Thumbnail Image", name: "thumbImg", widget: "image" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Order", name: "order", widget: "number" }
      - <<: *meta
      - { label: "Body", name: "body", widget: "markdown" }
