backend:
  name: github
  repo: Jaspero/zoldos-group
  branch: master
  base_url: https://europe-west2-zoldos-group.cloudfunctions.net/
  auth_endpoint: /oauth/auth
publish_mode: editorial_workflow

# Media files will be stored in the repo under docs/uploads
media_folder: "public/uploads"

# The src attribute for uploaded media will begin with /uploads
public_folder: "/uploads"


# Reusable blocks for all of the pages
blocks: &blocks
  label: "Blocks"
  name: "blocks"
  widget: "list"
  types:
    - label: "Text Block"
      name: "textBlock"
      widget: "object"
      fields:
        - { label: "Title", name: "title", widget: "string", required: false }
        - { label: "content", name: "content", widget: "markdown", required: false }

meta: &meta
  label: "Meta"
  name: "meta"
  widget: "object"
  fields:
    - { label: "Title", name: "title", widget: "string", required: false }
    - { label: "Description", name: "description", widget: "text", required: false }
    - { label: "Keywords", name: "keywords", widget: "string", required: false }


collections:
  - name: "settings"
    label: "Settings"
    extension: "json"
    format: "json"
    editor:
      preview: false
    files:
      - label: "Navigation"
        name: "Navigation"
        file: "public/collections/settings/navigation.json"
        fields:
          - label: "Links"
            name: "links"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "text" }
              - { label: "Link", name: "link", widget: "text" }

  - name: "pages"
    label: "Pages"
    extension: "json"
    format: "json"
    folder: "public/collections/pages"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - <<: *meta
      - <<: *blocks
